[package]
name = "helper-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "proc-macro"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
proc-macro-error = "1.0"
