use crate::utils::scope::define_scopes;

define_scopes! {
    GithubScopes;
    GithubScope {
        NoScope => "(no scope)",
        Repo => "repo",
        RepoStatus => "repo:status",
        RepoDeployment => "repo_deployment",
        PublicRepo => "public_repo",
        RepoInvite => "repo:invite",
        SecurityEvents => "security_events",
        AdminRepoHook => "admin:repo_hook",
        WriteRepoHook => "write:repo_hook",
        ReadRepoHook => "read:repo_hook",
        AdminOrg => "admin:org",
        WriteOrg => "write:org",
        ReadOrg => "read:org",
        AdminPublicKey => "admin:public_key",
        WritePublicKey => "write:public_key",
        ReadPublicKey => "read:public_key",
        AdminOrgHook => "admin:org_hook",
        Gist => "gist",
        Notifications => "notifications",
        User => "user",
        ReadUser => "read:user",
        UserEmail => "user:email",
        UserFollow => "user:follow",
        Project => "project",
        ReadProject => "read:project",
        DeleteRepo => "delete_repo",
        WritePackages => "write:packages",
        ReadPackages => "read:packages",
        DeletePackages => "delete:packages",
        AdminGpgKey => "admin:gpg_key",
        WriteGpgKey => "write:gpg_key",
        ReadGpgKey => "read:gpg_key",
        CodesSpace => "codespace",
        Workflow => "workflow",
    }
}
